name: Grant GitHub Actions permissions

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  permissions:
    runs-on: ubuntu-latest
    steps:
      - name: Check permissions
        run: echo "Permissions set for GitHub Pages deployment" 